In [3]:
import pandas as pd
from statistics import mean
from scipy.stats import ttest_rel
from scipy.stats import ttest_ind
import numpy as np

# GATHERING TRAIN METRIC RESULTS FROM ALL DATASETS

Reading the training csv of all datasets, rearranging table format, and finding the mean for each metric and algorithm combination.

In [2]:
adult = pd.read_csv("adult_train.csv")
adult = adult.drop(adult.iloc[:, :1], axis = 1).T
adult['Mean'] = adult.mean(axis=1)
adult.round(4)

                    0       1       2       3       4    Mean
LG: Accuracy   0.8254  0.8162  0.8032  0.8174  0.8148  0.8154
LG: Precision  0.3967  0.4304  0.4740  0.6583  0.5023  0.4923
LG: AUC        0.8329  0.8267  0.8174  0.8324  0.8269  0.8273
LG: F1         0.7079  0.6995  0.6830  0.6927  0.6990  0.6964
RF: Accuracy   1.0000  1.0000  1.0000  1.0000  1.0000  1.0000
RF: Precision  1.0000  1.0000  1.0000  1.0000  1.0000  1.0000
RF: AUC        1.0000  1.0000  1.0000  1.0000  1.0000  1.0000
RF: F1         1.0000  1.0000  1.0000  1.0000  1.0000  1.0000
DT: Accuracy   1.0000  1.0000  1.0000  1.0000  1.0000  1.0000
DT: Precision  1.0000  1.0000  1.0000  1.0000  1.0000  1.0000
DT: AUC        0.8514  0.8465  0.8441  0.8442  0.8441  0.8461
DT: F1         0.7169  0.7320  0.7224  0.7187  0.7162  0.7213

In [3]:
bank = pd.read_csv("bank_train.csv")
bank = bank.drop(bank.iloc[:, :1], axis = 1).T
bank['Mean'] = bank.mean(axis=1)
bank.round(4)

                    0       1       2       3       4    Mean
LG: Accuracy   0.8748  0.8818  0.8540  0.8444  0.8766  0.8663
LG: Precision  0.1258  0.6183  0.4261  0.1351  0.5678  0.3746
LG: AUC        0.8405  0.8380  0.8380  0.8192  0.8390  0.8350
LG: F1         0.5746  0.5836  0.5799  0.5490  0.5862  0.5747
RF: Accuracy   1.0000  1.0000  1.0000  1.0000  1.0000  1.0000
RF: Precision  1.0000  1.0000  1.0000  1.0000  1.0000  1.0000
RF: AUC        1.0000  1.0000  1.0000  1.0000  1.0000  1.0000
RF: F1         1.0000  1.0000  1.0000  1.0000  1.0000  1.0000
DT: Accuracy   1.0000  1.0000  1.0000  1.0000  1.0000  1.0000
DT: Precision  1.0000  1.0000  1.0000  1.0000  1.0000  1.0000
DT: AUC        0.8761  0.8711  0.8729  0.8701  0.8745  0.8729
DT: F1         0.7420  0.5810  0.5968  0.6547  0.6755  0.6500

In [4]:
employee = pd.read_csv("employee_train.csv")
employee = employee.drop(employee.iloc[:, :1], axis = 1).T
employee['Mean'] = employee.mean(axis=1)
employee.round(4)

                    0       1       2       3       4    Mean
LG: Accuracy   0.7536  0.7580  0.2394  0.4240  0.2404  0.4831
LG: Precision  0.3947  0.3848  0.3887  0.3979  0.3870  0.3906
LG: AUC        0.6605  0.6867  0.6724  0.6801  0.6578  0.6715
LG: F1         0.5259  0.5163  0.5164  0.5203  0.5129  0.5184
RF: Accuracy   0.9974  0.9970  0.9966  0.9966  0.9964  0.9968
RF: Precision  0.9888  0.9878  0.9860  0.9865  0.9860  0.9870
RF: AUC        0.9980  0.9980  0.9976  0.9977  0.9973  0.9977
RF: F1         0.9944  0.9938  0.9929  0.9932  0.9926  0.9934
DT: Accuracy   0.9972  0.9970  0.9966  0.9966  0.9398  0.9854
DT: Precision  0.9888  0.9878  0.9860  0.9865  0.9836  0.9865
DT: AUC        0.9515  0.9566  0.9492  0.9459  0.9416  0.9489
DT: F1         0.9944  0.9938  0.9929  0.9932  0.8805  0.9710

In [5]:
letterp1 = pd.read_csv("letterp1_train.csv")
letterp1 = letterp1.drop(letterp1.iloc[:, :1], axis = 1).T
letterp1['Mean'] = letterp1.mean(axis=1)
letterp1.round(4)

                    0       1       2       3       4    Mean
LG: Accuracy   0.8094  0.0364  0.9626  0.7774  0.8000  0.6772
LG: Precision  0.1501  0.1225  0.1316  0.1351  0.1417  0.1362
LG: AUC        0.8581  0.8277  0.8420  0.8359  0.8561  0.8440
LG: F1         0.2584  0.2170  0.2298  0.2351  0.2504  0.2381
RF: Accuracy   1.0000  1.0000  1.0000  1.0000  1.0000  1.0000
RF: Precision  1.0000  1.0000  1.0000  1.0000  1.0000  1.0000
RF: AUC        1.0000  1.0000  1.0000  1.0000  1.0000  1.0000
RF: F1         1.0000  1.0000  1.0000  1.0000  1.0000  1.0000
DT: Accuracy   1.0000  1.0000  1.0000  1.0000  1.0000  1.0000
DT: Precision  1.0000  1.0000  1.0000  1.0000  1.0000  1.0000
DT: AUC        0.9781  0.9698  0.9683  0.9726  0.9725  0.9723
DT: F1         1.0000  1.0000  0.9590  1.0000  1.0000  0.9918

In [6]:
letterp2 = pd.read_csv("letterp2_train.csv")
letterp2 = letterp2.drop(letterp2.iloc[:, :1], axis = 1).T
letterp2['Mean'] = letterp2.mean(axis=1)
letterp2.round(4)

                    0       1       2       3       4    Mean
LG: Accuracy   0.7282  0.7126  0.7350  0.7304  0.7324  0.7277
LG: Precision  0.6572  0.7014  0.7269  0.7285  0.7208  0.7070
LG: AUC        0.7286  0.7124  0.7351  0.7304  0.7319  0.7277
LG: F1         0.7324  0.7118  0.7348  0.7334  0.7362  0.7297
RF: Accuracy   1.0000  1.0000  1.0000  1.0000  1.0000  1.0000
RF: Precision  1.0000  1.0000  1.0000  1.0000  1.0000  1.0000
RF: AUC        1.0000  1.0000  1.0000  1.0000  1.0000  1.0000
RF: F1         1.0000  1.0000  1.0000  1.0000  1.0000  1.0000
DT: Accuracy   1.0000  1.0000  1.0000  0.9772  1.0000  0.9954
DT: Precision  1.0000  1.0000  1.0000  0.9922  1.0000  0.9984
DT: AUC        0.8888  0.9248  0.9060  0.8946  0.9050  0.9039
DT: F1         1.0000  1.0000  1.0000  1.0000  1.0000  1.0000

# MEAN TRAINING SET PERFORMANCE

Finding the mean training performance across five trials over five datasets.

In [7]:
table2 = pd.DataFrame(index=['Accuracy', 'Precision', 'ROC AUC', 'F1'], 
                      columns=['Logistic Regression', 'Random Forest', 'Decision Trees'])
for i in range(table2.shape[0]):
    # index number loops over metrics ['Accuracy', 'Precision', 'ROC AUC', 'F1']
    # Skips every four columns to get the corresponding learning algorithm with each metric
    table2['Logistic Regression'].iloc[i] = mean([bank['Mean'].iloc[i],adult['Mean'].iloc[i],letterp1['Mean'].iloc[i],
                                                  letterp2['Mean'].iloc[i],employee['Mean'].iloc[i]])
    table2['Random Forest'].iloc[i] = mean([bank['Mean'].iloc[i+4],adult['Mean'].iloc[i+4],letterp1['Mean'].iloc[i+4],
                                                  letterp2['Mean'].iloc[i+4],employee['Mean'].iloc[i+4]])
    table2['Decision Trees'].iloc[i] = mean([bank['Mean'].iloc[i+8],adult['Mean'].iloc[i+8],letterp1['Mean'].iloc[i+8],
                                                  letterp2['Mean'].iloc[i+8],employee['Mean'].iloc[i+8]])
    
table2 = table2.T
table2['Mean'] = table2.mean(axis=1)
table2.round(4)

                     Accuracy Precision   ROC AUC        F1    Mean
Logistic Regression  0.713936  0.420152  0.781081  0.551456  0.6167
Random Forest         0.99936  0.997401  0.999549  0.998675  0.9987
Decision Trees       0.996176  0.996992  0.908809  0.866801  0.9422

In [8]:
# Finding average metrics over each dataset
table3 = pd.DataFrame(columns=['Adult', 'Bank', 'Employee', 'Letter P1', 'Letter P2'], 
                      index=['Logistic Regression', 'Random Forest', 'Decision Trees'])
for i in range(table3.shape[0]):
    # index number loops over learning algorithms ['Logistic Regression', 'Random Forest', 'Decision Trees']
    # getting the mean of each dataset over all four metrics
    table3['Adult'].iloc[i] = mean(adult['Mean'].iloc[4*i:4*i+4])
    table3['Bank'].iloc[i] = mean(bank['Mean'].iloc[4*i:4*i+4])
    table3['Employee'].iloc[i] = mean(employee['Mean'].iloc[4*i:4*i+4])
    table3['Letter P1'].iloc[i] = mean(letterp1['Mean'].iloc[4*i:4*i+4])
    table3['Letter P2'].iloc[i] = mean(letterp2['Mean'].iloc[4*i:4*i+4])

table3['Mean'] = table3.mean(axis=1)
table3.round(4)

                        Adult      Bank  Employee Letter P1 Letter P2    Mean
Logistic Regression  0.707859  0.662639  0.515894  0.473863  0.723025  0.6167
Random Forest               1         1  0.993732         1         1  0.9987
Decision Trees       0.891828  0.880728  0.972969  0.991014  0.974434  0.9422

# GATHERING TEST METRIC RESULTS FROM ALL DATASETS

Reading the training csv of all datasets, rearranging table format, and finding the mean for each metric and algorithm combination.

In [4]:
adult = pd.read_csv("adult_test.csv")
adult = adult.drop(adult.iloc[:, :1], axis = 1).T
adult['Mean'] = adult.mean(axis=1)
adult.round(4)

                    0       1       2       3       4    Mean
LG: Accuracy   0.8074  0.8040  0.8069  0.8039  0.8023  0.8049
LG: Precision  0.3951  0.4072  0.4769  0.6556  0.4993  0.4868
LG: AUC        0.8163  0.8159  0.8172  0.8181  0.8162  0.8168
LG: F1         0.6824  0.6790  0.6823  0.6828  0.6775  0.6808
RF: Accuracy   0.8492  0.8491  0.8470  0.8487  0.8484  0.8485
RF: Precision  0.7337  0.7279  0.7317  0.7385  0.7275  0.7319
RF: AUC        0.7704  0.7732  0.7663  0.7716  0.7721  0.7707
RF: F1         0.6681  0.6711  0.6612  0.6691  0.6709  0.6681
DT: Accuracy   0.8051  0.8058  0.8058  0.8037  0.8037  0.8048
DT: Precision  0.6033  0.5922  0.6005  0.6074  0.6022  0.6011
DT: AUC        0.7959  0.7982  0.7919  0.8026  0.7966  0.7971
DT: F1         0.6514  0.6633  0.6552  0.6531  0.6535  0.6553

In [5]:
bank = pd.read_csv("bank_test.csv")
bank = bank.drop(bank.iloc[:, :1], axis = 1).T
bank['Mean'] = bank.mean(axis=1)
bank.round(4)

                    0       1       2       3       4    Mean
LG: Accuracy   0.8661  0.8773  0.8535  0.8564  0.8679  0.8642
LG: Precision  0.1329  0.5818  0.4236  0.1397  0.5661  0.3688
LG: AUC        0.8243  0.8262  0.8196  0.8306  0.8233  0.8248
LG: F1         0.5727  0.5647  0.5665  0.5715  0.5631  0.5677
RF: Accuracy   0.8925  0.8952  0.8936  0.8897  0.8932  0.8928
RF: Precision  0.7280  0.7180  0.7034  0.7274  0.7073  0.7168
RF: AUC        0.6627  0.6570  0.6802  0.6677  0.6651  0.6665
RF: F1         0.4859  0.5069  0.4937  0.4750  0.4811  0.4885
DT: Accuracy   0.8651  0.8614  0.8632  0.8635  0.8646  0.8636
DT: Precision  0.4630  0.4521  0.4516  0.4713  0.4736  0.4623
DT: AUC        0.8285  0.8193  0.8143  0.8218  0.7882  0.8144
DT: F1         0.5094  0.5181  0.5181  0.5160  0.5008  0.5125

In [6]:
employee = pd.read_csv("employee_test.csv")
employee = employee.drop(employee.iloc[:, :1], axis = 1).T
employee['Mean'] = employee.mean(axis=1)
employee.round(4)

                    0       1       2       3       4    Mean
LG: Accuracy   0.7661  0.7639  0.2374  0.4172  0.2369  0.4843
LG: Precision  0.3658  0.3690  0.3796  0.3912  0.3721  0.3755
LG: AUC        0.6489  0.6692  0.6593  0.6863  0.6481  0.6624
LG: F1         0.4958  0.4990  0.5063  0.5179  0.4922  0.5022
RF: Accuracy   0.9600  0.9574  0.9604  0.9617  0.9596  0.9598
RF: Precision  0.9079  0.9139  0.9186  0.9123  0.9204  0.9146
RF: AUC        0.9442  0.9372  0.9428  0.9463  0.9436  0.9428
RF: F1         0.9140  0.9097  0.9157  0.9187  0.9135  0.9143
DT: Accuracy   0.9396  0.9452  0.9441  0.9443  0.9331  0.9413
DT: Precision  0.8594  0.8780  0.8714  0.8669  0.8685  0.8688
DT: AUC        0.9297  0.9284  0.9341  0.9322  0.9249  0.9299
DT: F1         0.8736  0.8870  0.8818  0.8825  0.8673  0.8784

In [7]:
letterp1 = pd.read_csv("letterp1_test.csv")
letterp1 = letterp1.drop(letterp1.iloc[:, :1], axis = 1).T
letterp1['Mean'] = letterp1.mean(axis=1)
letterp1.round(4)

                    0       1       2       3       4    Mean
LG: Accuracy   0.8021  0.0381  0.9623  0.7875  0.7881  0.6756
LG: Precision  0.1483  0.1371  0.1324  0.1371  0.1385  0.1387
LG: AUC        0.8390  0.8432  0.8435  0.8345  0.8318  0.8384
LG: F1         0.2538  0.2346  0.2314  0.2373  0.2396  0.2394
RF: Accuracy   0.9885  0.9887  0.9901  0.9898  0.9870  0.9888
RF: Precision  0.9970  0.9591  0.9833  0.9914  0.9915  0.9844
RF: AUC        0.8368  0.8790  0.8696  0.8657  0.8420  0.8586
RF: F1         0.8299  0.8431  0.8577  0.8401  0.8068  0.8355
DT: Accuracy   0.9851  0.9837  0.9847  0.9843  0.9839  0.9843
DT: Precision  0.8346  0.7695  0.8151  0.8029  0.8242  0.8093
DT: AUC        0.9242  0.9305  0.9361  0.9279  0.9181  0.9274
DT: F1         0.7846  0.7880  0.7654  0.7649  0.7854  0.7777

In [8]:
letterp2 = pd.read_csv("letterp2_test.csv")
letterp2 = letterp2.drop(letterp2.iloc[:, :1], axis = 1).T
letterp2['Mean'] = letterp2.mean(axis=1)
letterp2.round(4)

                    0       1       2       3       4    Mean
LG: Accuracy   0.7262  0.7204  0.7279  0.7214  0.7240  0.7240
LG: Precision  0.6433  0.7176  0.7184  0.7202  0.7151  0.7029
LG: AUC        0.7265  0.7211  0.7278  0.7213  0.7252  0.7244
LG: F1         0.7301  0.7210  0.7314  0.7178  0.7271  0.7255
RF: Accuracy   0.9489  0.9507  0.9483  0.9481  0.9431  0.9478
RF: Precision  0.9459  0.9500  0.9534  0.9515  0.9470  0.9496
RF: AUC        0.9499  0.9507  0.9479  0.9477  0.9442  0.9481
RF: F1         0.9479  0.9501  0.9491  0.9458  0.9428  0.9471
DT: Accuracy   0.8873  0.8907  0.8967  0.8907  0.8867  0.8904
DT: Precision  0.8881  0.8912  0.8984  0.9077  0.8896  0.8950
DT: AUC        0.8528  0.8750  0.8619  0.8484  0.8538  0.8584
DT: F1         0.8843  0.8932  0.8944  0.8924  0.8865  0.8902

# TABLE 2

In [9]:
# Finding algorithm metrics over all 5 datasets
table2 = pd.DataFrame(index=['Accuracy', 'Precision', 'ROC AUC', 'F1'], 
                      columns=['Logistic Regression', 'Random Forest', 'Decision Trees'])
for i in range(table2.shape[0]):
    # index number loops over metrics ['Accuracy', 'Precision', 'ROC AUC', 'F1']
    # Skips every four columns to get the corresponding learning algorithm with each metric
    table2['Logistic Regression'].iloc[i] = mean([bank['Mean'].iloc[i],adult['Mean'].iloc[i],letterp1['Mean'].iloc[i],
                                                  letterp2['Mean'].iloc[i],employee['Mean'].iloc[i]])
    table2['Random Forest'].iloc[i] = mean([bank['Mean'].iloc[i+4],adult['Mean'].iloc[i+4],letterp1['Mean'].iloc[i+4],
                                                  letterp2['Mean'].iloc[i+4],employee['Mean'].iloc[i+4]])
    table2['Decision Trees'].iloc[i] = mean([bank['Mean'].iloc[i+8],adult['Mean'].iloc[i+8],letterp1['Mean'].iloc[i+8],
                                                  letterp2['Mean'].iloc[i+8],employee['Mean'].iloc[i+8]])
    
table2 = table2.T
table2['Mean'] = table2.mean(axis=1)
table2.round(4)

                     Accuracy Precision   ROC AUC        F1    Mean
Logistic Regression  0.710605  0.414565  0.773346  0.543115  0.6104
Random Forest        0.927549   0.85947   0.83735   0.77072  0.8488
Decision Trees       0.896866  0.727308  0.865417  0.742815  0.8081

In [10]:
table2_ttest = pd.DataFrame(index=['Accuracy', 'Precision', 'ROC AUC', 'F1'], 
                           columns=['LG', 'RF', 'DT'])
for i in range(4):
    # index number loops over metrics ['Accuracy', 'Precision', 'ROC AUC', 'F1']
    # Skips every four columns to get the corresponding learning algorithm with each metric
    # Gets the list of all the trial scores for the corresponding metrics
    
    # Logistic Regression
    val1 = np.concatenate([bank.iloc[i,:-1],adult.iloc[i,:-1],letterp1.iloc[i,:-1],
                           letterp2.iloc[i,:-1],employee.iloc[i,:-1]])
    # Random Forest
    val2 = np.concatenate([bank.iloc[i+4,:-1],adult.iloc[i+4,:-1],letterp1.iloc[i+4,:-1],
                           letterp2.iloc[i+4,:-1],employee.iloc[i+4,:-1]])
    # Decision Trees
    val3 = np.concatenate([bank.iloc[i+8,:-1],adult.iloc[i+8,:-1],letterp1.iloc[i+8,:-1],
                           letterp2.iloc[i+8,:-1],employee.iloc[i+8,:-1]])
    # Finding p-value using independent t-test
    if i == 2:
        table2_ttest['LG'].iloc[i] = ttest_ind(val3, val1)[1]
        table2_ttest['RF'].iloc[i] = ttest_ind(val3, val2)[1]
        table2_ttest['DT'].iloc[i] = float(1)
    else:
        table2_ttest['LG'].iloc[i] = ttest_ind(val2, val1)[1]
        table2_ttest['RF'].iloc[i] = float(1)
        table2_ttest['DT'].iloc[i] = ttest_ind(val2, val3)[1]

table2_ttest.T

       Accuracy    Precision      ROC AUC           F1
LG  2.58435e-05  3.60369e-12  6.08411e-06  3.07918e-05
RF            1            1     0.262249            1
DT     0.066122   0.00247935            1      0.54288

# TABLE 3

In [12]:
# Finding average metrics over each dataset
table3 = pd.DataFrame(columns=['Adult', 'Bank', 'Employee', 'Letter P1', 'Letter P2'], 
                      index=['Logistic Regression', 'Random Forest', 'Decision Trees'])
for i in range(table3.shape[0]):
    # index number loops over learning algorithms ['Logistic Regression', 'Random Forest', 'Decision Trees']
    # getting the mean of each dataset over all four metrics
    table3['Adult'].iloc[i] = mean(adult['Mean'].iloc[4*i:4*i+4])
    table3['Bank'].iloc[i] = mean(bank['Mean'].iloc[4*i:4*i+4])
    table3['Employee'].iloc[i] = mean(employee['Mean'].iloc[4*i:4*i+4])
    table3['Letter P1'].iloc[i] = mean(letterp1['Mean'].iloc[4*i:4*i+4])
    table3['Letter P2'].iloc[i] = mean(letterp2['Mean'].iloc[4*i:4*i+4])

table3['Mean'] = table3.mean(axis=1)
table3.round(4)

                        Adult      Bank  Employee Letter P1 Letter P2    Mean
Logistic Regression  0.697329  0.656393  0.506114  0.473017  0.719186  0.6104
Random Forest        0.754797  0.691171  0.932897  0.916847   0.94815  0.8488
Decision Trees       0.714578  0.663196  0.904595  0.874645  0.883494  0.8081

In [17]:
dataset = [adult, bank, employee, letterp1, letterp2]
table3_ttest = pd.DataFrame(index=['Adult', 'Bank', 'Employee', 'Letter P1', 'Letter P2'], 
                            columns=['LG', 'RF', 'DT'])
for i, data in enumerate(dataset):
    # index number loops over dataset ['Adult', 'Bank', 'Employee', 'Letter P1', 'Letter P2']
    # Get the list of all trail scores for the corresponding dataset
    # Skips every four columns to get the corresponding learning algorithm
    
    # Logistic Regression
    val1 = np.concatenate([data.iloc[:4,0],data.iloc[:4,1],data.iloc[:4,2],data.iloc[:4,3],data.iloc[:4,4]])
    # Random Forest
    val2 = np.concatenate([data.iloc[4:8,0],data.iloc[4:8,1],data.iloc[4:8,2],data.iloc[4:8,3],data.iloc[4:8,4]])
    # Decision Tree
    val3 = np.concatenate([data.iloc[8:12,0],data.iloc[8:12,1],data.iloc[8:12,2],data.iloc[8:12,3],data.iloc[8:12,4]])

    # Finding p-value using independent t-test
    table3_ttest['LG'].iloc[i] = ttest_ind(val2, val1)[1]
    table3_ttest['RF'].iloc[i] = float(1)
    table3_ttest['DT'].iloc[i] = ttest_ind(val2, val3)[1]
table3_ttest.T

       Adult      Bank     Employee    Letter P1    Letter P2
LG  0.114593   0.57316  3.43025e-14  1.67169e-06  7.87304e-38
RF         1         1            1            1            1
DT  0.119651  0.597412   0.00213068     0.106842  1.17304e-19